apiVersion: 1

datasources:
  - name: k6-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: ${INFLUXDB_USER}
    secureJsonData:
      password: ${INFLUXDB_USER_PASSWORD}
    database: ${INFLUXDB_DB}
    isDefault: true
    jsonData:
      timeInterval: 5s
      httpMode: POST
